# Autogenerated wrapper script for HarfBuzz_jll for x86_64-w64-mingw32
export libharfbuzz, libharfbuzz_gobject, libharfbuzz_icu, libharfbuzz_subset

using Glib_jll
using FreeType2_jll
using Graphite2_jll
using Libffi_jll
using Gettext_jll
using Fontconfig_jll
using Cairo_jll
using ICU_jll
JLLWrappers.@generate_wrapper_header("HarfBuzz")
JLLWrappers.@declare_library_product(libharfbuzz, "libharfbuzz-0.dll")
JLLWrappers.@declare_library_product(libharfbuzz_gobject, "libharfbuzz-gobject-0.dll")
JLLWrappers.@declare_library_product(libharfbuzz_icu, "libharfbuzz-icu-0.dll")
JLLWrappers.@declare_library_product(libharfbuzz_subset, "libharfbuzz-subset-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll, FreeType2_jll, Graphite2_jll, Libffi_jll, Gettext_jll, Fontconfig_jll, Cairo_jll, ICU_jll)
    JLLWrappers.@init_library_product(
        libharfbuzz,
        "bin\\libharfbuzz-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libharfbuzz_gobject,
        "bin\\libharfbuzz-gobject-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libharfbuzz_icu,
        "bin\\libharfbuzz-icu-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libharfbuzz_subset,
        "bin\\libharfbuzz-subset-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
